version: "3.8"
services:

  

  redis:
    image: "redis:alpine"

  web:
    build: .
    depends_on:
    
      - some-redis
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
      
